services: 

  mysql-db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=node-app-db
      - MYSQL_ROOT_PASSWORD=root
    ports: 
      - "3306:3306"
    networks: 
      - node-network

  node-app:
    build: 
      context: ./node-app
    container_name: node-app
    entrypoint: dockerize -wait tcp://mysql-db:3306 -timeout 20s docker-entrypoint.sh
    command: ["node","index.js"]
    networks: 
      - node-network
    volumes: 
      - ./node-app:/usr/src/app
      - /usr/src/app/node_modules
    environment: 
      - MYSQL_HOST=mysql-db
    tty: true
    ports: 
      - "3000:3000"

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - node-network
    ports: 
      - "8080:80"
    
networks: 
  node-network:
    driver: bridge